### PR TITLE
Fix search on hidden columns in samples table [SCI-813]

### PR DESCRIPTION
**Pull request by Ducz0r**
Closes [SCI-813](https://biosistemika.atlassian.net/browse/SCI-813).

### CODE REVIEW

**Comment by mlorb** [comment]
Sorry, but I can't make it work... the search still displays rows with hidden sample items.

**Comment by Ducz0r** [comment]
Works for me... @mz3944, can you review this?

**Comment by mz3944** [comment]
Same her, doesn't work :/.

**Comment by Ducz0r** [comment]
@mz3944, would it be acceptable if I just clear the searched text if you toggle columns visibility? Re-initializing table on each visibility toggle is costly, and has some weird consequences (shortly, it doesn't work as it should).

**Comment by Ducz0r** [comment]
Nevermind, found an elegant solution.

**Pull request merged**
