### PR TITLE
Fix user has no teams view [SCI-1033]

### PR DESCRIPTION
**Pull request by mlorb**
https://biosistemika.atlassian.net/browse/SCI-1033

Other part:
http://gitlab.biosistemika.com/scinote/organization_management/merge_requests/16

### CODE REVIEW

**Comment by Ducz0r** [comment]
Sorry to be the devil's advocate here, but this should only be true in the `organization_management` addon, not in this codebase (if you're using sciNote core, you CAN create new teams on your own, therefore this text here makes sense). I suggest to open a PR in `organization_management`, and close this PR 🙁.

**Comment by mlorb** [comment]
Ok, I messed it up. :(
Maybe the first line of text can be changed here on core anyway?

**Comment by mlorb** [comment]
And I also added the needed data-hooks.

**Comment by Ducz0r** [comment]
Very nice, :ship: away!

**Pull request merged**
