### PR TITLE
Fix first time data generator & fake data generator

### PR DESCRIPTION
**Pull request by Ducz0r**
This MR includes the following fixes:
* adds activities for creation of comments in first time tutorial (first time data generator),
* fixes a bug in organization.rb for calculationg space taken,
* adds activities for creation of comments in fake data generator, as well as fix it so it works with the changes introduced in experiment level.

### CODE REVIEW

**Comment by Ducz0r** [comment]
No idea why Hound checks failed.

**Comment by Ducz0r** [comment]
I just remembered - I believe I forgot to generate workflow images once the data is seeded.

**Comment by jbargu** [comment]
It is in first time generator but not in fake generator.

**Comment by jbargu** [comment]
Looks good though, although I cannot randomize an experiment, all projects are empty, but this isn't connected with this PR, so I guess you can just :ship: :it:

**Pull request merged**
