### PR TITLE
Move tooltip to the right [fixes SCI-591]

### PR DESCRIPTION
**Pull request by ZmagoD**
https://biosistemika.atlassian.net/browse/SCI-591

### CODE REVIEW

**Comment by mlorb** [comment]
sci_591
Now team name on the button is not ok.

**Comment by ZmagoD** [comment]
Do you have the last commit 9214adc?

**Comment by mlorb** [comment]
No, I missed it. But now maybe it would be better to move tooltip a little bit more right, because I still don't see the whole name of the other team.
sci-591-2

**Comment by mlorb** [comment]
And I discovered another problem with displaying long names of teams in dropdown. Maybe you can handle this one as well? :)
sci-591-x

**Comment by mlorb** [comment]
Ok, let's leave some work for testers ;) Merge away :ship:

**Pull request merged**
