### PR TITLE
Refactor & restyle the API authorization screen [SCI-2859]

### PR DESCRIPTION
**Pull request by okriuchykhin**
https://biosistemika.atlassian.net/browse/SCI-2859

### CODE REVIEW

**Comment by mz3944** [comment]
So I can only test this via LinkedIn button right? But how do I get it? I had it before, but I don't know what combination of addons I need for LinkedIn button to become available.

**Comment by mz3944** [comment]
When I click on the LinkedIn button I get:
`You need to pass the "client_id" parameter`
Am I missing some environment variable/s?

**Comment by okriuchykhin** [comment]
This page is for Doorkeeper OAuth authorisations, it has nothing to do with LinkedIn.
https://github.com/doorkeeper-gem/doorkeeper

**Comment by mz3944** [comment]
How can I test it? I don't want to waste time reading the docs, so if there is a straightforward way, please provide me with the info. I need to set some environment variables?

**Comment by okriuchykhin** [comment]
It should redirect back to the app with error description(for native apps it just renders error)

**Comment by Ducz0r** [comment]
Cool, then you can merge this :+1:.

**Pull request merged**
