### PR TITLE
Comments date duplication

### PR DESCRIPTION
**Pull request by ZmagoD**
https://biosistemika.atlassian.net/browse/SCI-469

### CODE REVIEW

**Comment by Ducz0r** [comment]
Good work, seems nice!

I only have a remark - on project comments, the edit options are displayed weirdly out of place (must be something in `comments.js`, I believe there are 2 ways on how is this `<div>` is positioned). If that's fixed (maybe it's not even related), this is ready for merge :+1:.

**Comment by ZmagoD** [comment]
I had also fixed the drop down position

**Comment by Ducz0r** [comment]
That `useParentOffset` parameter is there for comments that are used on canvas (task comments). With your last commit, you broke comment editing for those comments, so I suggest reverting and finding alternative solution.

**Comment by Ducz0r** [comment]
I think you just have to pass the `useParentOffset = true` parameter when initializing comments editing on home page (projects page).

**Comment by ZmagoD** [comment]
that do the job thank you!

**Pull request merged**
