### PR TITLE
  Move comment box in Protocol and Results (in  Task s) out of the  Comments tab

### PR DESCRIPTION
**Pull request by ZmagoD**
https://biosistemika.atlassian.net/browse/SCI-436

### CODE REVIEW

**Comment by mz3944** [comment]
When you edit comment, the page jumps to top and then back to the comment. If you cancel edit, its stays at top of the page. Since this does not effect the functionality, we can just open a new issue for this.

**Comment by mz3944** [comment]
When you edit a step, comments disappear.

**Comment by mz3944** [comment]
Comments on project should have "more Comments" on top of them, not at the bottom.

**Comment by ZmagoD** [comment]
is a bit jumpy because of the comment drobdown functions . This need some refactoring but the other remark you made on my comp the comments stays there

**Comment by ZmagoD** [comment]
this issue was about the steps and results comment

**Comment by mz3944** [comment]
Ah, I though that other messages were left out, my bad.

**Comment by ZmagoD** [comment]
what we do next....

**Comment by mz3944** [comment]
Will try to test it with S3 file uploading, I'm suspecting you're using S3, thats why it works for you.

**Comment by ZmagoD** [comment]
?????

**Comment by ZmagoD** [comment]
so should we push it

**Comment by mz3944** [comment]
Even with S3 the comments disappear after edit...

**Comment by mz3944** [comment]
When you solve this, or if you can't reproduce it you can try if it works on production server, and if it works, open a bottle of beer!

**Comment by ZmagoD** [comment]
uff on chrome and mozilla works perfectly

**Comment by mz3944** [comment]
If it works for you, we can risk it, and testers will report it if it exists for them too. So I guess I have to, with a deep regret, accept this pull request. Merge it. Just do it!

**Comment by ZmagoD** [comment]
Let ship that . . .

**Pull request merged**
