### PR TITLE
adds edit workflow link if no workflow [fixes SCI-374]

### PR DESCRIPTION
**Pull request by ZmagoD**
https://biosistemika.atlassian.net/browse/SCI-374

### CODE REVIEW

**Comment by Ducz0r** [comment]
I've reviewed this PR. Looks good, I only have 2 remarks (you can probably ignore the last one):
* This PR introduces a bug that is (at least on my machine) not present on `master`. If you press "Add a task to experiment...`, you are presented with Edit canvas screen. But **cancel** button doesn't work (it keeps you in the edit mode). So that should be fixed.
* Throughout most of application, we have a different way of saying text is blank - e.g. "No comments!", "No description", ... So maybe that would be a preferred way to handle this?

**Comment by Ducz0r** [comment]
After you fix the mentioned bug, this seems ready for merge to me :+1:.

**Comment by ZmagoD** [comment]
@Ducz0r I fixed the canvas related bug can you check if it works on your machine?

**Comment by Ducz0r** [comment]
It works now! Looks good for merge to me! :+1:

**Pull request merged**
