### PR TITLE
Refactored .js.erb -> .js using gon gem [SCI-2620]

### PR DESCRIPTION
**Pull request by Zanz2**

### CODE REVIEW

**Comment by Zanz2** [comment]
Fixed what I could of hound, the gon is not defined is not correct, its defined in controllers, and the "dont use parentheses around literals" is either that or line too long, because aligning it to many lines without parentheses gives syntax error.

**Comment by Zanz2** [comment]
Travis CI fails, i spent 2 extra hours trying to debug it, the causes are
Gon.global.HIGHLIGHTJS_GITHUB_THEME = ::ActionController::Base.helpers.asset_path('highlightjs-github-theme')
and
  Gon.global.RAILS_URL_HELPER_TINY_MCE_ASSETS_PATH = tiny_mce_assets_path

Need to find a right place to place them, because they dont work when placed in gon_constants or application controller, especially not with common addon where for some reason routes dont get resolved in application controller of non addon scinote.

**Comment by Zanz2** [comment]
Will continue with this once dev team returns :D

**Comment by Zanz2** [comment]
A possible solution to the two issues with link helpers not being available at certain parts of execution is just hardcoding the two links, but we probably really dont want this.

**Comment by okriuchykhin** [comment]
@Zanz2 please fix conflicts and tests

**Comment by Ducz0r** [comment]
@Zanz2 I've updated this branch with my pull request. Basically, can you just re-check if everything works? Then we can merge this one.

**Comment by Ducz0r** [comment]
⚠️ When merging, be sure to also fix `app/assets/javascripts/protocols/steps.js.erb` (which was modified in a recently opened PR #1289).

**Comment by Zanz2** [comment]
Ran the tests, after #1289 is merged, I will change its implementation to use gon gem in this branch

**Pull request closed without merging**
