### PR TITLE
Fix adding new samples columns [SCI-779]

### PR DESCRIPTION
**Pull request by okriuchykhin**
https://biosistemika.atlassian.net/browse/SCI-779

### CODE REVIEW

**Comment by mlorb** [comment]
If you change the order of columns directly on table, in drop-down column order doesn't update.

**Comment by mlorb** [comment]
The ordering works, but visibility changes after refresh.

**Comment by okriuchykhin** [comment]
Fixed those issues, should be fine now

**Comment by mlorb** [comment]
Great job!
Mergeaway :tada:

**Pull request merged**
