### PR TITLE
Edit&delete comments

### PR DESCRIPTION
**Pull request by Ducz0r**
New feature allows editing & deleting comments from projects, modules/tasks, protocol steps and results.

### CODE REVIEW

**Comment by jbargu** [comment]
When you remove the last comment, it should say 'No comment' like when no comments.

**Comment by jbargu** [comment]
It would be cool if you could see, if some edited comment and when.

**Comment by jbargu** [comment]
When editing comments on canvas, right after insert a comment, the dropdown will be misplaced. The more comments, the more it'll be misplaced. However if you open the comment window, dropdown is correctly placed.

**Comment by jbargu** [comment]
When editing protocol and then trying to either edit/delete a comment, nothing will happen.

**Comment by jbargu** [comment]
Jolly good, besides the above remarks, works as a charm. Here have a :cake:

**Comment by Ducz0r** [comment]
Nice finds! I fixed everything you found, with the exception of suggestion for last edit timestamp & user. It's not in the specifications. I believe we can implement that one day, but it's not today :smile_cat:.

**Pull request merged**
