### PR TITLE
Added additional activities [SCI-605]

### PR DESCRIPTION
**Pull request by okriuchykhin**
https://biosistemika.atlassian.net/browse/SCI-605

### CODE REVIEW

**Comment by mlorb** [comment]
load protocol from file is not working anymore

**Comment by mlorb** [comment]
For sample un/assign activity, you get in the activity log the list of all selected samples. There should be written only those samples that are being un/assigned (their previous state should be checked).

**Comment by okriuchykhin** [comment]
Fixed samples assign/unassign logic

**Comment by mlorb** [comment]
The problem is still present, if you assign already assigned sample (the same with unassigned ones).

**Comment by mlorb** [comment]
great, works as expected... merge away :+1:

**Pull request merged**
