### PR TITLE
Move dropdown container to left [SCI-3203]

### PR DESCRIPTION
**Pull request by aignatov-bio**
Jira ticket: https://biosistemika.atlassian.net/browse/SCI-3203

### What was done
Move dropdown container to left

### CODE REVIEW

**Comment by urbanrotnik** [comment]
@aignatov-bio check Travis

**Comment by aignatov-bio** [comment]
It's not my error :)

**Comment by urbanrotnik** [comment]
@aignatov-bio 
Looks good in chrome but in Safari: 

When I resize the screen to smaller, click on input not shows dropdown anymore and I never get focus.
No JS error.

**Comment by urbanrotnik** [comment]
Fix is coming in next PR. By @aignatov-bio

**Pull request merged**
