### PR TITLE
Automatically resize textarea elements [SCI-637]

### PR DESCRIPTION
**Pull request by Ducz0r**
This MR includes a jQuery addon that allows for automatic resizing of `<textarea>` elements.

It took me some time to figure out a styling solution that correctly renders the "add comment" buttons on Firefox & Chrome...

### CODE REVIEW

**Comment by mlorb** [comment]
When editing task description, text-area resizing is not working correctly. The same problem is with edit experiment details, edit checklists and save edited report.
textarea_resize

**Comment by Ducz0r** [comment]
@mlorb, is it better now?

**Comment by mlorb** [comment]
Works perfectly, great job :+1: :icecream:

**Comment by Ducz0r** [comment]
Yay! 🎉

**Pull request merged**
