### PR TITLE
fixes new task button after tutorial ends

### PR DESCRIPTION
**Pull request by ZmagoD**
quick fix that enables back the "new task button"

### CODE REVIEW

**Comment by mz3944** [comment]
It doesn't work for me, because ajaxComplete doesn't work. Use onAjaxComplete from utils.js instead, which replaces it.

**Comment by jbargu** [comment]
Nope, still not working.

**Comment by ZmagoD** [comment]
SCI-401  #close

**Comment by jbargu** [comment]
What a lifesaver! Merge ASAP! :+1:

**Pull request merged**
