### PR TITLE
Fixed tables getting cut when certain attributes are at max length [SCI-1834]

### PR DESCRIPTION
**Pull request by Zanz2**
Step description, step expected result, protocol description, protocol manuscript citation, protocol guidelines, protocol warning and protocol before start attributes all now dont get cut tables if they exceed the character limit and have a table included (the table now doesnt get cut, even though text will)

### CODE REVIEW

**Comment by mlorb** [comment]
Import protocol preview and imported protocol are differently cutted off. Check where is the problem.

**Comment by mlorb** [comment]
The scrollbar is now separated from the table, that you are scrolling.

**Comment by mlorb** [comment]
The problem with the separated scrollbar is still present, if the table is smaller then the fixed height.

**Comment by mlorb** [comment]
I realized that this bug was introduced with some other fix, not this PR. That's why you don't need to fix it in this PR. Darja will create a new jira task for it.

**Comment by Zanz2** [comment]
removed last commit (width 300px) and am now merging into master

**Pull request merged**
